### ISSUE TITLE
Random Database [central] not configured errors

### ISSUE THREAD

**Issue by thevalo** [stancl/tenancy#981]
### Bug description

Sometimes, randomly the server returns a 500 error, stating `Database connection [central] not configured.`.

What I've known is that it happens more often when the web server is started, and I am initially opening the "login" page.
But it throws random errors here-and-there, maaybe (if this is not biased) when refreshing/opening multiple pages at once (connection closing problems?)

### Steps to reproduce

To be honest, there's not any specific steps, but generally:

1. Install the package,
2. Create a tenant
3. Act as a tenant
4. Execute queries on `central` database from tenant 

### Expected behavior

These seemingly-innocent errors should not happen in a normal deployed server.

Here's the full log:
```
[2022-10-19 10:16:13] local.ERROR: Database connection [central] not configured. {"exception":"[object] (InvalidArgumentException(code: 0): Database connection [central] not configured. at C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php:161)
[stacktrace]
#0 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php(124): Illuminate\\Database\\DatabaseManager->configuration('central')
#1 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php(95): Illuminate\\Database\\DatabaseManager->makeConnection('central')
#2 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1653): Illuminate\\Database\\DatabaseManager->connection('central')
#3 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1619): Illuminate\\Database\\Eloquent\\Model::resolveConnection('central')
#4 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1425): Illuminate\\Database\\Eloquent\\Model->getConnection()
#5 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1342): Illuminate\\Database\\Eloquent\\Model->newBaseQueryBuilder()
#6 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1378): Illuminate\\Database\\Eloquent\\Model->newModelQuery()
#7 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1331): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()
#8 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1321): Illuminate\\Database\\Eloquent\\Model->newQuery()
#9 C:\\laragon\\www\\[redacted]\\vendor\\stancl\\tenancy\\src\\Resolvers\\DomainTenantResolver.php(35): Illuminate\\Database\\Eloquent\\Model::query()
#10 C:\\laragon\\www\\[redacted]\\vendor\\stancl\\tenancy\\src\\Resolvers\\Contracts\\CachedTenantResolver.php(34): Stancl\\Tenancy\\Resolvers\\DomainTenantResolver->resolveWithoutCache('XXX.XXX...')
#11 C:\\laragon\\www\\[redacted]\\vendor\\stancl\\tenancy\\src\\Middleware\\IdentificationMiddleware.php(26): Stancl\\Tenancy\\Resolvers\\Contracts\\CachedTenantResolver->resolve('XXX.XXX...')
#12 C:\\laragon\\www\\[redacted]\\vendor\\stancl\\tenancy\\src\\Middleware\\InitializeTenancyByDomain.php(38): Stancl\\Tenancy\\Middleware\\IdentificationMiddleware->initializeTenancy(Object(Illuminate\\Http\\Request), Object(Closure), 'XXX.XXX...')
#13 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Stancl\\Tenancy\\Middleware\\InitializeTenancyByDomain->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 C:\\laragon\\www\\[redacted]\\vendor\\stancl\\tenancy\\src\\Middleware\\PreventAccessFromCentralDomains.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Stancl\\Tenancy\\Middleware\\PreventAccessFromCentralDomains->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#22 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#23 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#24 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#25 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#26 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 C:\\laragon\\www\\[redacted]\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 C:\\laragon\\www\\[redacted]\\vendor\\itsgoingd\\clockwork\\Clockwork\\Support\\Laravel\\ClockworkMiddleware.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 C:\\laragon\\www\\[redacted]\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#46 C:\\laragon\\www\\[redacted]\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#47 {main}
"} 
```

### Laravel version

8.54

### stancl/tenancy version

3.5

**Comment by stancl** [comment]
Hey!

Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.

If you need quick support, you can visit our Discord community here: https://archte.ch/discord

The issue here is likely that you are telling tenancy to use the `central` connection but you didn't create it in `config/database.php`. If you did, then make sure your config cache in production is up to date.

Thanks

**Comment by thevalo** [comment]
> Hey!
> 
> Thanks for opening the issue. This doesn't seem to be a bug in package, seems to be related to your setup.
> 
> If you need quick support, you can visit our Discord community here: https://archte.ch/discord
> 
> The issue here is likely that you are telling tenancy to use the `central` connection but you didn't create it in `config/database.php`. If you did, then make sure your config cache in production is up to date.
> 
> Thanks

Hello, thanks for the quick reply.

I have nowhere defined `central` connection, I merely thought that it's managed by the package itself. Strange, though. It happens only acting on central domain from the tenant's context.

**Comment by stancl** [comment]
It's not. It uses `DB_CONNECTION` https://github.com/archtechx/tenancy/blob/3.x/assets/config.php#L42 by default and if you want to use a custom one, you can set it in this config.

The package manages the `tenant` connection, but it needs a central connection to work with — it has no way to create that.

**Comment by thevalo** [comment]
Hi once again,

as far as I can comprehend, I think this one has to do still with the package. I can reassure that nowhere I have a "central" connection. Please ignore this thread w/o hesitation if you feel like it's ok on the package side, you know, I have no real proof that it's coming from the package.

However, please see the following screenshot:
![screenshot1](https://user-images.githubusercontent.com/28608203/201606097-e123b3fc-ee6f-4407-9ecd-64c9b526d5e8.png)

Sorry for any incovenience caused. I am not finding anything related in the internet about this problem. On other projects, it does not happen at all.

**Comment by stancl** [comment]
Check that the environment variable and the config key I linked are set properly.

**Comment by thevalo** [comment]
The current value of `DB_CONNECTION` in my `.env` is `mysql`, so it's: `DB_CONNECTION=mysql`. 

I am not sure if I can comprehend what should I verify.

EDIT: so in the `tenancy.php` config file, I should modify the `central` value akin to `.env`, meaning `mysql`?

**Comment by stancl** [comment]
I'm asking what the config key looks like, not saying you should modify it.

**Comment by thevalo** [comment]
It is exactly the same as you've shown in the link: `'central_connection' => env('DB_CONNECTION', 'central'),`

**Comment by stancl** [comment]
No idea then, something else must be misconfigured on your end.

**Comment by thevalo** [comment]
Shouldn't that be exactly as "DB_DONNECTION" of the `.env`? Maybe a cache miss here-and-there, and when it can't get the value from `.env` using `env()` method, it gets "central" DB even though it's not correct. 

Thank you for assistance, though.
